version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: summary
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
